// apps/monicandavid.com/src/routes/+page.svelte
<script lang="ts">
import {css} from 'styled-system/css'

const title = 'monicandavid.com'
</script>

<svelte:head>
  <title>{title}</title>
  <meta name="description" content={title} />
</svelte:head>

<main
  class={css({
    minHeight: '100vh',
    display: 'grid',
    placeItems: 'center',
    fontFamily: 'sans',
    bg: 'white',
    color: 'neutral.900',
  })}
>
  <h1 class={css({fontSize: '5xl', fontWeight: 'bold', letterSpacing: 'tight'})}>{title}</h1>
</main>

// apps/startchi.com/src/routes/index.tsx
import {createFileRoute} from '@tanstack/react-router'

import {css} from 'styled-system/css'

export const Route = createFileRoute('/')({
  component: Home,
})

function Home() {
  return (
    <main className={css({minHeight: '100vh', display: 'grid', placeItems: 'center'})}>
      <h1 className={css({fontSize: '5xl', fontWeight: 'bold', letterSpacing: 'tight'})}>
        startchi.com
      </h1>
    </main>
  )
}
